baseURL = "https://mnlscn.github.io/"
languageCode = "en"
title = "Manuel Scionti | AI Engineer"

[params]
  description = "AI Engineer specializing in LLMs and Generative AI"
  author = "Manuel Scionti"
  github = "https://github.com/mnlscn"
  linkedin = "https://www.linkedin.com/in/manuelscionti/"
  email = "your.email@example.com"
  location = "Barcelona, Spain"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
